### ISSUE TITLE
Scalar with multiple arguements

### ISSUE THREAD

**Issue by lena** [absinthe-graphql/absinthe#258] opened 2017-01-31 19:58 UTC
We are trying to build a scalar type by converting the below object: 
```
object :timeline_datapoint do
  field :time, :time
  field :value, :float
end
```

This is what we've got so far, but it's not working:
```
scalar :timeline_datapoint do
  parse fn e -> Poison.Decoder.decode(e) end
  serialize fn d -> Poison.Encoder.encode(%{time: d.time, value: d.value}, []) end
end
```

This is the error we are getting: 
```
no function clause matching in Absinthe.Schema.concrete_types/2
```
Any advice?

**Comment by benwilson512** [comment] 2017-01-31 20:02
Hey there!

I need a bit more context to understand what you're doing. Can you show a GraphQL query you're trying to run, as well as all field definitions that that query hits?

How are you using those types?

**Comment by lena** [comment] 2017-02-07 21:45
Sorry for the delay.

Please find the schema below:
```
 object :timeline_dataset do
   field :points, list_of(:timeline_datapoint)
   field :points_last_year, list_of(:timeline_datapoint)
 end

 object :timeline_datapoint do
   field :time, :string
   field :value, :float
 end
```

We have defined the `timeline_datapoint` as an object type. But, this is causing an issue at the iOs client side (Apollo) because it ends up generating duplicate objects of same type with different names.

This is causing duplicate object types that contain the same fields, namely, `Points` and `PointsLastYear`. We spoke to the author of the `[apollo library](https://github.com/apollographql/apollo-ios)` and it seems that we need to use the custom scalar type to avoid duplication.

When we tried to define a custom scalar type, we could not get the code to compile, as shown in original post. 

Please advise.

**Comment by bruce** [comment] 2017-02-07 22:10
@lena That definitely sounds like a strange problem (we use Apollo); the issue is that both `points` and `pointsLastYear` have the same types?

Regardless, using Absinthe v1.2.X, please try this for your scalar:

```elixir
scalar :timeline_datapoint do
  parse fn e -> Poison.decode(e.value) end
  serialize fn d -> Poison.encode!(%{time: d.time, value: d.value}) end
end
```

- Note the `.value` -- the argument to `parse` is a struct
- `parse` should return an `{:ok, value}` tuple -- or `:error`
- `serialize` should just return the serialized value

For more info, please see [the guide](http://absinthe-graphql.org/guides/custom-scalars/).

Do let us know if this helps or if we can be of further assistance.

**Comment by bruce** [comment] 2017-02-20 07:51
Closing; please reopen if this is still an issue.

**Closed by bruce** 2017-02-20 07:51 UTC
