### ISSUE TITLE
Incorrect Enum validation for default value of the input object field 

### ISSUE THREAD

**Issue by kuznetskikh** [absinthe-graphql/absinthe#1165] opened 2022-03-23 02:10 UTC
### Environment

* Elixir 1.13.0
* Absinthe 1.6.7

### Expected behavior

In my schema I'm trying to specify enum using shorthand with list of allowed values, like:

`enum :color_channel, values: [:red, :green, :blue, :alpha]`

And then in input object I'm trying to add default value, like:

`field(:color_channel, :color_channel, default_value: :red)`

### Actual behavior

While validating my schema Absinthe fails with such error:
`
** (ArgumentError) you attempted to apply a function named :value on [::red, :green, :blue, :alpha]. If you are using Kernel.apply/3, make sure the module is an atom. If you are using the dot syntax, such as map.field or module.function(), make sure the left side of the dot is an atom or a map
    :erlang.apply([:red, :green, :blue, :alpha], :value, [])
    (absinthe 1.6.7) lib/absinthe/phase/schema/validation/default_enum_value_present.ex:33: anonymous fn/1 in Absinthe.Phase.Schema.Validation.DefaultEnumValuePresent.validate_defaults/2
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (absinthe 1.6.7) lib/absinthe/phase/schema/validation/default_enum_value_present.ex:33: Absinthe.Phase.Schema.Validation.DefaultEnumValuePresent.validate_defaults/2
    (absinthe 1.6.7) lib/absinthe/blueprint/transform.ex:16: anonymous fn/3 in Absinthe.Blueprint.Transform.prewalk/2
    (absinthe 1.6.7) lib/absinthe/blueprint/transform.ex:109: Absinthe.Blueprint.Transform.walk/4
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir 1.13.0) lib/enum.ex:1715: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
`

Line 33 from default_enum_value_present.ex:
`values = Enum.map(enum.values, & &1.value)`

So enum doesn't have `value` because of the shorthand used. I think validation should support any form of `enum` declaration.

**Comment by benwilson512** [comment] 2022-03-23 02:11
This is a duplicate of https://github.com/absinthe-graphql/absinthe/issues/1081

**Closed by benwilson512** 2022-03-23 02:11 UTC

**Comment by kuznetskikh** [comment] 2022-03-23 02:15
Oh, I see, just missed it. Thanks @benwilson512 !
