### ISSUE TITLE
GraphQL schema generation not work

### ISSUE THREAD

**Issue by fazibear** [absinthe-graphql/absinthe#127] opened 2016-07-18 17:40 UTC
`mix absinthe.schema.graphql` or returns something like this

```
* creating .
* creating ./schema.graphql
** (File.Error) could not write to file "./schema.graphql": bad argument
    (elixir) lib/file.ex:716: File.write!/3
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

Elixir 1.3.2
OTP 19.0

**Comment by fazibear** [comment] 2016-07-23 20:57
Tried to fix it: https://github.com/absinthe-graphql/absinthe/pull/131

**Comment by benwilson512** [comment] 2016-07-24 20:36
Hey! IOdata is a perfectly valid thing to send to a file, so there isn't any need to do the Enum.join thing. Can you show the full stack trace along with the schema you're trying to write?

**Comment by fazibear** [comment] 2016-07-24 20:56
Here you are:
```["schema {\n", ["  query: query\n", "  mutation: mutation\n", ""], "}\n",
 [["type ", :mutation, [], " {\n",
   [[[" ", " "],
     ["registerUserWithFacebook",
      ["(", [["accessToken", ": ", ["String", "!"], ""]], ")"], ": ", "User"],
     "\n"]], "}\n"],
  ["enum ", "Quality", " {\n",
   [[[" ", " "], "HIGH", "\n"], [[" ", " "], "LOW", "\n"],
    [[" ", " "], "MEDIUM", "\n"]], "}\n"],
  ["type ", :query, [], " {\n",
   [[[" ", " "], ["publicVideos", [], ": ", ["[", "Video", "]"]], "\n"]],
   "}\n"],
  ["type ", "User", [], " {\n",
   [[[" ", " "], ["email", [], ": ", "String"], "\n"],
    [[" ", " "], ["id", [], ": ", "ID"], "\n"],
    [[" ", " "], ["name", [], ": ", "String"], "\n"]], "}\n"],
  ["type ", "Video", [], " {\n",
   [[[" ", " "], ["id", [], ": ", "ID"], "\n"],
    [[" ", " "],
     ["thumbUrl", ["(", [["quality", ": ", "Quality", ""]], ")"], ": ",
      "String"], "\n"],
    [[" ", " "],
     ["url", ["(", [["quality", ": ", "Quality", ""]], ")"], ": ", "String"],
     "\n"]], "}\n"]]]```

**Comment by fazibear** [comment] 2016-07-24 21:14
Found a problem. When you name `query` or `mutation` with symbol it will break. 
Here is example:

```
  query(name: :query) do
    ...
  end
```

**Comment by bruce** [comment] 2016-07-25 01:28
As intended. The value of `:name` should be of type `String.t` and no conversion occurs implicitly from an atom. This is also true on other types (eg, `object`, `union`, `enum`, etc). We should check this type in the future, but this is not expected behavior.

You should use the following if you want your query type to be named "Query" (by default it is named "RootQueryType"):

```elixir
query name: "Query" do
  # ...
end
```

**Comment by fazibear** [comment] 2016-07-25 08:15
Also graphql schema generation will break if I try to include types to schema:

```
  import_types App.Absinthe.Types.Video
  import_types App.Absinthe.Types.User
```

But there is no `App.Absinthe.Types` module defined.

```
** (ArgumentError) argument error
    :erlang.binary_to_existing_atom("Elixir.App.Absinthe.Types", :utf8)
    (elixir) src/elixir_aliases.erl:108: :elixir_aliases.safe_concat/1
    (absinthe) lib/absinthe/type.ex:36: Absinthe.Type.built_in?/1
    (elixir) lib/enum.ex:1674: anonymous fn/3 in Enum.reject/2
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1674: Enum.reject/2
    (absinthe) lib/absinthe/language/idl.ex:9: Absinthe.Language.IDL.to_idl_ast/1
    (absinthe) lib/mix/tasks/absinthe.schema.graphql.ex:59: Mix.Tasks.Absinthe.Schema.Graphql.run/1
```

To fix this, you have to define empty `App.Absinthe.Types` module.

**Comment by bruce** [comment] 2016-09-11 07:35
Closing this as there's a know workaround (and I haven't been able to reproduce this final issue). IDL generation should be wholely revamped after the v1.2 release anyway.

**Closed by bruce** 2016-09-11 07:35 UTC
